services:
  ldap:
    build:
      context: ./Dockerfile/
      dockerfile: Dockerfile
    image: ldap:latest
    container_name: ldap
    hostname: ldap
    volumes:
      - ./conf/:/usr/local/openldap/dist:ro
      - ./volumes/ldap/slapd.d:/usr/local/openldap/etc/openldap/slapd.d:rw
      - ./volumes/ldap/data:/usr/local/openldap/var/openldap-data:rw
      - ./volumes/backups/ldap:/backups:rw
